# .github/workflows/test-vault.yml
name: Test Vault Generic Flow
on:
  push:
    branches: [ "vault-login","main" ]
  workflow_dispatch: # Îl pornești tu manual din butonul de GitHub Actions

jobs:
  vault-login:
    uses: ./.github/workflows/vault-login.yaml

  test-vault:
    needs: vault-login
    runs-on: ubuntu-latest
    steps:
      - name: Verify Secrets (Safe Check)
        run: |
          if [ -z "${{ needs.vault-login.outputs.auth }}" ]; then
            echo "❌ Secretul nu a fost preluat!"
            exit 1
          else
            echo "✅ Succes! Variabilele sunt în pipeline."
          fi
