# .github/workflows/test-vault.yml
name: Test Vault Generic Flow
on:
  push:
    branches: [ "vault-login","main" ]
  workflow_dispatch: # Îl pornești tu manual din butonul de GitHub Actions

jobs:
  test-vault:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: voltronet/actions/vault-login@main
        with:
          app_name: 'backend-service'
          environment: 'local' # Sau staging, pentru a testa logica de non-prod
          vault_token: ${{ secrets.VAULT_TOKEN_DEV }}

      - name: Verify Secrets (Safe Check)
        run: |
          if [ -z "$DRCARMEN_UNLEASH_AUTHORIZATION" ]; then
            echo "❌ Secretul nu a fost preluat!"
            exit 1
          else
            echo "✅ Succes! Variabilele sunt în pipeline."
          fi
